### ISSUE TITLE
This problem occurred when I was training. Why

### ISSUE THREAD

**Issue by NNNEFIT3** [HpWang-whu/RoReg#1]
(torch)user@ul1:/anaconda3/envs/torch/RoReg$ python trainset.py --component GFTraceback (most recent call last):
File "trainset.py" , line 1, in<module>
import parses. parses gf as parses gf
NoduleNotFoundError: No module named 'Parses.parses_gf"'

**Comment by HpWang-whu** [comment]
Hi @NNNEFIT3,  thanks for your interest in our work!
I have already fixed the bug and updated the code. Sorry for the inconvenience.

Best wishes.

**Comment by NNNEFIT3** [comment]
Thank you very much for providing the updated code.I have already debugged it. but I passed this command when training the dataset:"PythonTrain.py --component GF". It prompts me that the data entered is not in the correct shape. The following is the output of the program board:

       train set len 2282
       val set len 187
       | 0/11410 [00:00<?, ?it/s]Traceback (most recent call last):
       File "/home/rst/anaconda3/envs/roreg/RoReg-master/network/group_feat.py", line 23, in data_process
       data=torch.reshape(data,[data.shape[0],data.shape[1],60,13])
       RuntimeError: shape '[32, 32, 60, 13]' is invalid for input of size 47923200
        | 0/11410 [00:08<?, ?it/s]

I don't know where the problem is. Some progress bars did not reach 100% when generating the validation set. I'm not sure if this has an impact or is there a problem with the code? 

Looking forward to receiving your reply.

**Comment by NNNEFIT3** [comment]
I think you have done a great job! So I want to achieve it faster.

**Comment by HpWang-whu** [comment]
Hi @NNNEFIT3,
The `batch_size` in `parses/parses_train_gf.py` should be set to 1, meaning use one batch file in one forward. 
https://github.com/HpWang-whu/RoReg/blob/cc91a0f26951af2d738428913996728224d117dc/parses/parses_train_gf.py#L62-L63
The size of training batch is set to 32 in 'train/trainset/GF_ET.py'. I will reorganize the code later to avoid such an ambiguity.

About the validation set generation, is there any specific error reported?

Best,

**Comment by NNNEFIT3** [comment]
Yes, there were no special errors reported regarding the generation of validation sets, only a warning message:

     RoReg-master/backbone/fcgf/misc.py:96: UserWarning: To copy construct from a tensor, it is recommended to use 
     sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
     coords = torch.tensor(coords, dtype=torch.int32)

Then I modified the code to change torch.tensor( ) to  torch.as_tensor( ), and the warning disappeared.

I found it time-consuming to generate a validation set, so I modified the batch_ Size, maybe this is the reason.I will modify it again.thank you very much.

Best  wishes.
