### ISSUE TITLE
Preprocessed dataset

### ISSUE THREAD

**Issue by zhaoyiww** [HpWang-whu/RoReg#2]
Hi, thanks for the amazing work! I have questions about your preprocessed 3DMatch datasets. Are the keypoints generated from the work FCGF? And I notice you mentioned keypoint detection in the Method section of the paper, so I also wonder how these keypoints (from the preprocessed datasets) are used in your algorithm.
Best regards

**Comment by HpWang-whu** [comment]
Hi @zhaoyiww，
Thanks for your interest in our work!
Yes, we use the same preprocessed data as FCGF\SpinNet\YOHO. 
We first extract RoReg-Desc on the randomly sampled ‘’keypoints‘’ in the preprocessed data (5k in each scan). Then, we conduct keypoint selection utilizing these RoReg-Desc.

Yours,

**Comment by zhaoyiww** [comment]
Thanks for the reply!
