### ISSUE TITLE
How should I train my dataset?

### ISSUE THREAD

**Issue by wyaimyj** [HpWang-whu/RoReg#3]
Hello, I would like to use your model to train on my own dataset. My dataset consists of point clouds from different viewpoints of a statue. However, I do not have the corresponding rotation and translation matrices between the point clouds pairwise. How can I address this issue? Thank you!

**Comment by HpWang-whu** [comment]
Hi @wyaimyj,
Thanks for your interest and please refer to https://github.com/HpWang-whu/YOHO/issues/9#issuecomment-1659693817.
Yours,
