### ISSUE TITLE
Error occurs at the fourth step,"python setup.py install --blas=... --blas=..."

### ISSUE THREAD

**Issue by bigdatasz** [HpWang-whu/RoReg#5]
Hello,Mr HpWang.When trying to complie the code,I trapped by a problem at the fourth step.The final line of the error information show:
File "/home/shenzhen/anaconda3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
My deep learning environment:ubuntu20.04 cuda11.1 cudnn8.0 pytorch1.7.1 torchvision0.8.2 torchaudio0.7.2 python3.7 gcc7 g++7 Anaconda3 
I ask for your helping hand,please.Thank you very much!

**Comment by HpWang-whu** [comment]
Hi @bigdatasz ，
You might follow [here](https://github.com/NVIDIA/MinkowskiEngine#cuda-11x) to install the latest version of MinkowskiEngine and there are some solved issues in [Mink](https://github.com/NVIDIA/MinkowskiEngine) focusing on this problem.

Yours,

**Comment by bigdatasz** [comment]
Thank you very much
