### ISSUE TITLE
How could I test my own dataset using your model pth?

### ISSUE THREAD

**Issue by wang89280** [HpWang-whu/RoReg#7]
Could you tell how to implementation this code?  I want to test my teeth dataset.

I would appreciate it.

**Comment by HpWang-whu** [comment]
Hi @wang89280,
You can follow the readme.md to install and utilize RoReg.
A more detailed introduction of extracting and using RoReg(YOHO descriptor) can be found [here](https://github.com/HpWang-whu/YOHO/blob/master/others/Readme.md).

Yours,

**Comment by wang89280** [comment]
I have now installed RoReg as per your request and successfully tested it with the demo data. The registration results of the demo data are problem-free. Currently, I'm using your model to test my own data. Firstly, I used the yoho_extract.py code from RoReg to extract the YOHO features, and I've saved these as cloud_bin_0Keypoints.txt, cloud_bin_0Keypoints.npy, cloud_bin_1Keypoints.txt, and cloud_bin_1Keypoints.npy. Then, I ran the YOHO_testset.py code with this data to generate the test data. Finally, I executed the Demo.py file. The registration result I obtained is incorrect, failing to align properly. 

I'm not sure where the issue lies, so I'd appreciate your help in reviewing this. Thank you so much for your assistance, it means a lot. 

Yours.I look forward to your response!

Below image is  wrong transform matrix:
![image](https://github.com/HpWang-whu/RoReg/assets/24508092/86ec15c2-1371-41f5-ae50-b3ff331fa65e)

Below image is wrong result:
![image](https://github.com/HpWang-whu/RoReg/assets/24508092/03f2c3ec-75fb-4932-be4b-6b8d86489a54)

Below is my data:
[kitchen.zip](https://github.com/HpWang-whu/RoReg/files/13870156/kitchen.zip)

**Comment by HpWang-whu** [comment]
Hi @wang89280,
Thanks for your interest!
I have run the data you offer and find that the provided keypoints are aggregated, causing the registration failure.
I have updated the ```dataops/dataset.py``` to randomly sample keypoints and now you can use RoReg without given kpt files.
Delete the 'Keypoints' dir now and place your pc files in the data dir like this:
![img_v3_0272_9ac42df8-884a-4d28-9ac3-ac4a522a3a2g](https://github.com/HpWang-whu/RoReg/assets/57579033/9033fe0e-0e5f-4554-a8aa-c99ea738450c)

Then, modify the demo file like this according to your point cloud size (I found that yohoc can achieve more accurate result on your dataset and yohoo is also ok).
![img_v3_0272_a6f3bc7c-6cf9-458b-83e5-0981b3991aeg](https://github.com/HpWang-whu/RoReg/assets/57579033/f853c502-964b-45c3-8d06-d8cc35b3b958)

Then you should obtain the result like this:
![img_v3_0272_890b5011-1a5d-43c2-8135-ba7118bd607g](https://github.com/HpWang-whu/RoReg/assets/57579033/9cbc6e7d-0d64-4423-b827-1b7358c171ae)
and
![img_v3_0272_34c1fb4c-6639-4324-b23b-687638048ffg](https://github.com/HpWang-whu/RoReg/assets/57579033/a81225aa-198d-4dd7-a862-8d80a2a26dfa)

Yours,

**Comment by wang89280** [comment]
I try to run code, but I failed.
It's really a pity.
