### ISSUE TITLE
CUDA11.4

### ISSUE THREAD

**Issue by nxgfn** [HpWang-whu/RoReg#8]
What should I do if the environment setup fails when I use cuda11.4 version but there is no pytorch compatible with 11.4?

**Comment by ghost** [comment]
try to use other version of cuda in conda？

**Comment by ghost** [comment]
> What should I do if the environment setup fails when I use cuda11.4 version but there is no pytorch compatible with 11.4?

or u can compile pytorch from source with cuda 11.4

**Comment by HpWang-whu** [comment]
I have updated the code to use a KNN matcher compatible with CUDA 11.4.
