### ISSUE TITLE
关于旋转等变特征到旋转不变特征计算的一个问题

### ISSUE THREAD

**Issue by ghost** [HpWang-whu/RoReg#9]
感谢诸位的杰出工作！当我在学习贵组发表的论文RoReg: Pairwise Point Cloud Registration With Oriented Descriptors and Local Rotations时，对于旋转等变特征到旋转不变特征计算的计算有一个困惑的点：旋转等变特征的60xn特征图，每一个旋转是对60行中某些行的置换操作，那么计算旋转不变特征时似乎应该进行的是对每一列取均值池化形成1xn的特征？但论文中的表述是“computed by average pooling on the F along the row direction”，这让我感到不解，这样操作似乎并没有消除置换的影响？我在查看您在该项目提供的代码后，也发现似乎是将bnxfxgn的特征图转为了bnxf，如果f表示特征维度，似乎是我的理解是正确的。如果方便的话，希望您能帮我解答一下这个疑惑！或者我有没有完全理解到位的地方，也希望您能不吝赐教！
祝好！

**Comment by HpWang-whu** [comment]
Hi @XZRRRRRR,
你的理解没问题的，我们“along the row direction”也可以理解成“among the rows”。担心有歧义，我们也在文章中表示了特征的维度。

Yours，

**Comment by ghost** [comment]
> Hi @XZRRRRRR, 你的理解没问题的，我们“along the row direction”也可以理解成“among the rows”。担心有歧义，我们也在文章中表示了特征的维度。
> 
> Yours，

好的！感谢您的及时解答！
